### PR TITLE
Update deploy scripts

### PR DESCRIPTION
**Pull request by hswopeams**

### CODE REVIEW

**Comment by zajck** [comment]
Please update also `contracts/.env.example` to include `DAI_TOKEN`

**Review by zajck — CHANGES_REQUESTED** [review]
Please update also contracts/.env.example to include DAI_TOKEN, otherwise deployment fails.

**Review by zajck — DISMISSED** [review]

**Review by bidyut-arianelabs — DISMISSED** [review]
Looks good to me 👍

**Review by zajck — CHANGES_REQUESTED** [review]
Constructor argument for `ERC1155NonTransferable` in `scripts/verify.ts` should be updated too.

**Review by zajck — APPROVED** [review]

**Review by bidyut-arianelabs — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
