### PR TITLE
CAS-03M: Inefficiency & Duplication of Code

### LINKED ISSUE #184: CAS-03M: Inefficiency & Duplication of Code
## CAS-03M: Inefficiency & Duplication of Code

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Code Style](/appendix/finding-types#code-style) | <span class="o-severity o-minor">Minor</span> | [Cashier.sol:L293-L334](https://github.com/bosonprotocol/contracts/blob/817b6814e4e93939fe237c525107f23ad67ce2da/contracts/Cashier.sol#L293-L334), [L340-L382](https://github.com/bosonprotocol/contracts/blob/817b6814e4e93939fe237c525107f23ad67ce2da/contracts/Cashier.sol#L340-L382) |

### Description:

The linked functions as well as other segments of the codebase suffer from heavy repetition and can be significantly reduced in both complexity and length by refactoring the code to utilize `internal` functions that perform the same state changes as requested and take advantage of `if-else` structures.

### Example:

```solidity
/**
 * @notice Following function `releasePayments`, if certain conditions for the voucher status are met, the voucher price will be sent to the seller
 * @param voucherDetails keeps all required information of the voucher which the payment should be released for.
 */
function releasePaymentToSeller(VoucherDetails memory voucherDetails)
    internal
{
    if (
        voucherDetails.paymentMethod == ETHETH ||
        voucherDetails.paymentMethod == ETHTKN
    ) {
        escrow[voucherDetails.holder] = escrow[voucherDetails.holder].sub(
            voucherDetails.price
        );
    }
    if (
        voucherDetails.paymentMethod == TKNETH ||
        voucherDetails.paymentMethod == TKNTKN
    ) {
        address addressTokenPrice =
            IVoucherKernel(voucherKernel).getVoucherPriceToken(
                voucherDetails.tokenIdSupply
            );

        escrowTokens[addressTokenPrice][
            voucherDetails.holder
        ] = escrowTokens[addressTokenPrice][voucherDetails.holder].sub(
            voucherDetails.price
        );
    }

    voucherDetails.price2issuer = voucherDetails.price2issuer.add(
        voucherDetails.price
    );

    IVoucherKernel(voucherKernel).setPaymentReleased(
        voucherDetails.tokenIdVoucher
    );

    LogAmountDistribution(
        voucherDetails.tokenIdVoucher,
        voucherDetails.issuer,
        voucherDetails.price,
        PaymentType.PAYMENT
    );
}

/**
 * @notice Following function `releasePayments`, if certain conditions for the voucher status are met, the voucher price will be sent to the buyer
 * @param voucherDetails keeps all required information of the voucher, which the payment should be released for.
 */
function releasePaymentToBuyer(VoucherDetails memory voucherDetails)
    internal
{
    if (
        voucherDetails.paymentMethod == ETHETH ||
        voucherDetails.paymentMethod == ETHTKN
    ) {
        escrow[voucherDetails.holder] = escrow[voucherDetails.holder].sub(
            voucherDetails.price
        );
    }

    if (
        voucherDetails.paymentMethod == TKNETH ||
        voucherDetails.paymentMethod == TKNTKN
    ) {
        address addressTokenPrice =
            IVoucherKernel(voucherKernel).getVoucherPriceToken(
                voucherDetails.tokenIdSupply
            );

        escrowTokens[addressTokenPrice][
            voucherDetails.holder
        ] = escrowTokens[addressTokenPrice][voucherDetails.holder].sub(
            voucherDetails.price
        );
    }

    voucherDetails.price2holder = voucherDetails.price2holder.add(
        voucherDetails.price
    );

    IVoucherKernel(voucherKernel).setPaymentReleased(
        voucherDetails.tokenIdVoucher
    );

    LogAmountDistribution(
        voucherDetails.tokenIdVoucher,
        voucherDetails.holder,
        voucherDetails.price,
        PaymentType.PAYMENT
    );
}
```

### Recommendation:

We advise this to be done so to greatly simplify the attack surface of the Cashier and increase its maintainability.

## Remediation Strategy

- [x] Refactor / combine `releasePaymentToBuyer` and `releasePaymentToSeller`  into a single `releasePayment` method with an enum argument for buyer or seller. The bulk of these two methods are the same, and the details that vary can be chosen based on this enum.

### PR DESCRIPTION
**Pull request by zajck**
Resolves https://github.com/bosonprotocol/contracts/issues/184

### CODE REVIEW

**Review by bidyut-arianelabs — CHANGES_REQUESTED** [review]
Looks good. I have added a small question.

**Review by cliffhall — DISMISSED** [review]
LGTM! 👍

**Review by mischat — DISMISSED** [review]
Nice to see that this didn't require any additional tests :)

great work people, feels nice to be able to refactor

**Review by bidyut-arianelabs — APPROVED** [review]
Looks good to me 👍

**Review by mischat — APPROVED** [review]
LGTM ... There is a trailing space which we can fix in another PR

**Pull request merged**
