### PR TITLE
BRR-06C: Variable Mutability Specifiers

### LINKED ISSUE #182: BRR-06C: Variable Mutability Specifiers
## BRR-06C: Variable Mutability Specifiers

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Gas Optimization](/appendix/finding-types#gas-optimization) | <span class="o-severity o-informational">Informational</span> | [BosonRouter.sol:L42-L44](https://github.com/bosonprotocol/contracts/blob/817b6814e4e93939fe237c525107f23ad67ce2da/contracts/BosonRouter.sol#L42-L44), [L115-L117](https://github.com/bosonprotocol/contracts/blob/817b6814e4e93939fe237c525107f23ad67ce2da/contracts/BosonRouter.sol#L115-L117) |

### Description:

The linked variables are assigned to only once during the contract's `constructor`.

### Example:

```solidity
/**
 * @notice Construct and initialze the contract. Iniialises associated contract addresses
 * @param _voucherKernel address of the associated VocherKernal contract instance
 * @param _tokenRegistry address of the associated TokenRegistry contract instance
 * @param _cashierAddress address of the associated Cashier contract instance
 */
constructor(
    address _voucherKernel,
    address _tokenRegistry,
    address _cashierAddress
) {
    notZeroAddress(_voucherKernel);
    notZeroAddress(_tokenRegistry);
    notZeroAddress(_cashierAddress);

    voucherKernel = _voucherKernel;
    tokenRegistry = _tokenRegistry;
    cashierAddress = _cashierAddress;
}
```

### Recommendation:

We advise them to be set as `immutable` greatly optimizing their read access gas cost.

## Remediation Strategy
The contracts whose addresses are set only in the constructor may later be superseded, should vulnerabilities be found and new versions deployed. Rather than following the recommendation to add immutable to the state variables, which would require this contract be redeployed along with any of those other contracts, we can avoid that by adding setters for the values so that the contract owner can update the addresses after launch.

- [x] Add `ownerOnly` modified setters for each of the `voucherKernel`, `tokenRegistry`, and `cashierAddress` contract address vars
- [x] Add unit tests for setters

### PR DESCRIPTION
**Pull request by bidyut-arianelabs**
This PR solves https://github.com/bosonprotocol/contracts/issues/182

### CODE REVIEW

**Review by cliffhall — DISMISSED** [review]
LGTM! 👍

**Review by mischat — CHANGES_REQUESTED** [review]
I think it is cleaner to make the suggested changes. thanks

**Review by zajck — CHANGES_REQUESTED** [review]
Please move the tests to `7_ admin_functionality` since this kind of functionalities are tested there.

**Review by zajck — CHANGES_REQUESTED** [review]

**Review by zajck — DISMISSED** [review]

**Review by cliffhall — APPROVED** [review]
LGTM! 👍

**Review by mischat — APPROVED** [review]

**Pull request merged**
