### PR TITLE
Revert when no state changes or events

### PR DESCRIPTION
**Pull request by zajck**
This PR adds require statements to functions, which until now gracefully executed even if they did emitted any event or change contract state.

Unit tests were adjusted so they expect revert reason instead of checking that state was not changed and no events were emitted.

### CODE REVIEW

**Review by cliffhall — DISMISSED** [review]
LGTM! 👍

**Review by hswopeams — CHANGES_REQUESTED** [review]
Request for one change and one question.

**Review by hswopeams — DISMISSED** [review]

**Review by mischat — DISMISSED** [review]
LGTM

**Review by bidyut-arianelabs — APPROVED** [review]
Looks good to me 👍

**Review by hswopeams — APPROVED** [review]

**Pull request merged**
