### PR TITLE
Deployment script changes

### PR DESCRIPTION
**Pull request by hswopeams**
Changed deploy.ts and related config files to enable deploying the ERC1155NonTransferable conditional commit token from a different address than the rest of the contracts

### CODE REVIEW

**Review by zajck — DISMISSED** [review]

**Review by bidyut-arianelabs — CHANGES_REQUESTED** [review]
Also there are changes in `package-lock.json` without adding any new changes in `package.json`.

**Review by bidyut-arianelabs — DISMISSED** [review]
Looks good to me 👍

**Review by zajck — DISMISSED** [review]

**Review by mischat — DISMISSED** [review]
LGTM

**Review by zajck — APPROVED** [review]

**Review by bidyut-arianelabs — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
