### PR TITLE
Publish npm package

### PR DESCRIPTION
**Pull request by dohaki**
This adds a GitHub workflow to publish the contracts and relevant files as a package to npm. The workflow is triggered if a new release is created. The version number of the package gets taken from the git tag. For older releases, we would need to publish manually though.

Would appreciate some feedback on the package name `@bosonprotocol/contracts` and included files if they make sense. The only thing that bothers me with the package name `@bosonprotocol/contracts` is that you would have to import like this
```js
// In Solidity
import "@bosonprotocol/contracts/contracts/interfaces/IBosonRouter.sol"
// In JS
import ABI from "@bosonprotocol/contracts/abi/contracts/BosonRouter.json"
```
Maybe a package name like `@bosoprotocol/core` is better? The you would not have the word `contracts` doubled in every import:
```js
// In Solidity
import "@bosonprotocol/core/contracts/interfaces/IBosonRouter.sol"
// In JS
import ABI from "@bosonprotocol/core/abi/contracts/BosonRouter.json"
```

**TODO: Add the env var `NPM_TOKEN` with respective privileges to `Settings > Secrets`.**

### CODE REVIEW

**Review by damir-bajramovic — CHANGES_REQUESTED** [review]
I am not sure what is the intended way of using this package. Is it like the contracts from `OpenZeppelin`?

I don't see an `.npmignore` file which is kinda important. If that file is missing, the `.gitignore` file is used by default.

Do we want to expose the ABIs with this package? If so, we need to push them to the npm registry by excluding them from the `.npmignore` file. 

Also, I believe that ABIs are used in a bunch of different places. It would be nice to publish them separately to the NPM registry, so we can pull them without pulling the rest of the code from this repository. 
We could automate the process when pushing new versions of the contracts to the `main` branch or something. 
Something similar can be witnessed in the `ethers` repository. They are using multiple packages as dependencies in one repository. Feel free to explore the structure.

**Review by damir-bajramovic — DISMISSED** [review]

**Review by hswopeams — COMMENTED** [review]
Is there a way to test this to make sure it only publishes releases and not pre-release tags?

**Comment by hswopeams** [comment]
> @hswopeams
> 
> > Is there a way to test this to make sure it only publishes releases and not pre-release tags?
> 
> I tested it on a fork https://github.com/dohaki/bosonprotocol-contracts. But the workflow currently triggers on every release AND pre-release created. See
> 
> https://github.com/bosonprotocol/contracts/blob/fdca3b65b73dcb37addf593752ebdda2b196dd5d/.github/workflows/publish.yaml#L2-L4
> 
> Here are the events which can be used https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#release. But I think it makes sense to also publish pre-releases. I mean the version suffix `-rc.X` implies that the package is a pre-release. And the main reason why I added this was because we had to manually update the ABIs in multiple places for testing the new contracts. If we would only publish releases then we would still need to do this.
> 
> What I could do though is to add a separate publish workflow. So we would have
> 
> 1. `Publish Pre-Releases`
> 
> * Triggered for pre-releases only
> * Uses [npm dist tag](https://docs.npmjs.com/adding-dist-tags-to-packages) `next` or similar
> 
> 1. `Publish Releases`
> 
> * Triggered for releases only
> * Uses default npm dist tag `latest`

I don't agree we should push pre-releases. There's a reason they're not releases. We will discuss this in the protocol team and make a decision.

**Comment by dohaki** [comment]
@hswopeams 
> I don't agree we should push pre-releases. There's a reason they're not releases. We will discuss this in the protocol team and make a decision.

Ok, thanks. Let me know how I should proceed. Just to be clear: with pre-release, I am referring to https://github.com/bosonprotocol/contracts/releases/tag/v1.0.0-rc.1 for example. I don't see a reason why we would have `v1.0.0-rc.1` published on GitHub but not on npm 🤔 

> The npm registry should NOT be updated every time we merge with main. Every main merge is NOT a release.

That is also not what I intended. As I said, the workflow is only triggered if you create a release or pre-release. So basically it would have been triggered for every listed release/pre-release you can find here https://github.com/bosonprotocol/contracts/releases and not on every merge to main.

**Review by mischat — APPROVED** [review]
This looks good to me. I like the idea of building into GHA and streamlining our contract integrations is a must for us.

**Review by mischat — CHANGES_REQUESTED** [review]
Is there nothing we can do about the /contracts/contracts ... can we not configure the job to take all of the files from the ./contracts folder ?

**Review by mischat — DISMISSED** [review]
This is as discussed and as expected; this looks good to me.

**Review by damir-bajramovic — DISMISSED** [review]

**Review by mischat — APPROVED** [review]
LGTM!

**Pull request merged**
